version: '3.11'
services:
  django:
    image: test
    container_name: django
    volumes:
      - .:/server
    build: .
    ports:
      - "8000:8000"
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
    command: python manage.py runserver 0.0.0.0:8000
  redis:
    image: "redis:alpine"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"