# Generated by Django 4.1.2 on 2023-01-08 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat2users',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='chat2users',
            name='user',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.RemoveField(
            model_name='message',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.DeleteModel(
            name='Chat2Users',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
